//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KChat.KChatWcfService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="KChatWcfService.IKWcfService", CallbackContract=typeof(KChat.KChatWcfService.IKWcfServiceCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IKWcfService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKWcfService/SendFile", ReplyAction="http://tempuri.org/IKWcfService/SendFileResponse")]
        void SendFile(string sender, byte[] file, string filePath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKWcfService/SendFile", ReplyAction="http://tempuri.org/IKWcfService/SendFileResponse")]
        System.Threading.Tasks.Task SendFileAsync(string sender, byte[] file, string filePath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKWcfService/Login", ReplyAction="http://tempuri.org/IKWcfService/LoginResponse")]
        void Login(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKWcfService/Login", ReplyAction="http://tempuri.org/IKWcfService/LoginResponse")]
        System.Threading.Tasks.Task LoginAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKWcfService/Logout", ReplyAction="http://tempuri.org/IKWcfService/LogoutResponse")]
        void Logout();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKWcfService/Logout", ReplyAction="http://tempuri.org/IKWcfService/LogoutResponse")]
        System.Threading.Tasks.Task LogoutAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKWcfService/GetTasks", ReplyAction="http://tempuri.org/IKWcfService/GetTasksResponse")]
        System.Data.DataTable GetTasks(string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKWcfService/GetTasks", ReplyAction="http://tempuri.org/IKWcfService/GetTasksResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetTasksAsync(string user);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IKWcfServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IKWcfService/RecieveFile")]
        void RecieveFile(string sender, byte[] file, string fileName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IKWcfServiceChannel : KChat.KChatWcfService.IKWcfService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KWcfServiceClient : System.ServiceModel.DuplexClientBase<KChat.KChatWcfService.IKWcfService>, KChat.KChatWcfService.IKWcfService {
        
        public KWcfServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public KWcfServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public KWcfServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public KWcfServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public KWcfServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void SendFile(string sender, byte[] file, string filePath) {
            base.Channel.SendFile(sender, file, filePath);
        }
        
        public System.Threading.Tasks.Task SendFileAsync(string sender, byte[] file, string filePath) {
            return base.Channel.SendFileAsync(sender, file, filePath);
        }
        
        public void Login(string username) {
            base.Channel.Login(username);
        }
        
        public System.Threading.Tasks.Task LoginAsync(string username) {
            return base.Channel.LoginAsync(username);
        }
        
        public void Logout() {
            base.Channel.Logout();
        }
        
        public System.Threading.Tasks.Task LogoutAsync() {
            return base.Channel.LogoutAsync();
        }
        
        public System.Data.DataTable GetTasks(string user) {
            return base.Channel.GetTasks(user);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetTasksAsync(string user) {
            return base.Channel.GetTasksAsync(user);
        }
    }
}
