//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KChat.KChatWcfService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="KChatWcfService.IKWcfService")]
    public interface IKWcfService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKWcfService/SendFile", ReplyAction="http://tempuri.org/IKWcfService/SendFileResponse")]
        void SendFile(string sender, byte[] file, string filePath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKWcfService/SendFile", ReplyAction="http://tempuri.org/IKWcfService/SendFileResponse")]
        System.Threading.Tasks.Task SendFileAsync(string sender, byte[] file, string filePath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKWcfService/Login", ReplyAction="http://tempuri.org/IKWcfService/LoginResponse")]
        void Login(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKWcfService/Login", ReplyAction="http://tempuri.org/IKWcfService/LoginResponse")]
        System.Threading.Tasks.Task LoginAsync(string username);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IKWcfServiceChannel : KChat.KChatWcfService.IKWcfService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KWcfServiceClient : System.ServiceModel.ClientBase<KChat.KChatWcfService.IKWcfService>, KChat.KChatWcfService.IKWcfService {
        
        public KWcfServiceClient() {
        }
        
        public KWcfServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KWcfServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KWcfServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KWcfServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SendFile(string sender, byte[] file, string filePath) {
            base.Channel.SendFile(sender, file, filePath);
        }
        
        public System.Threading.Tasks.Task SendFileAsync(string sender, byte[] file, string filePath) {
            return base.Channel.SendFileAsync(sender, file, filePath);
        }
        
        public void Login(string username) {
            base.Channel.Login(username);
        }
        
        public System.Threading.Tasks.Task LoginAsync(string username) {
            return base.Channel.LoginAsync(username);
        }
    }
}
